// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkA2BrnNekKmz7CTwqd917p4CUpb_Ayeg',
    appId: '1:403559483702:android:534fd28ca14fdfc7958b97',
    messagingSenderId: '403559483702',
    projectId: 'cineflutterdb',
    storageBucket: 'cineflutterdb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCYODWbkemLa0YV61JNNixfCtr7t5CZ34',
    appId: '1:403559483702:web:96896ede73787a0c958b97',
    messagingSenderId: '403559483702',
    projectId: 'cineflutterdb',
    authDomain: 'cineflutterdb.firebaseapp.com',
    storageBucket: 'cineflutterdb.firebasestorage.app',
    measurementId: 'G-T23P1CQXDW',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCYODWbkemLa0YV61JNNixfCtr7t5CZ34',
    appId: '1:403559483702:web:29ab0ea412c593bd958b97',
    messagingSenderId: '403559483702',
    projectId: 'cineflutterdb',
    authDomain: 'cineflutterdb.firebaseapp.com',
    storageBucket: 'cineflutterdb.firebasestorage.app',
    measurementId: 'G-2BPDH5Q74G',
  );

}